#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01)

if [ "$#" -eq 1 ]; then
    dig "www.$1" | grep -A1 'ANSWER SECTION:' | awk '{print "The subdomain www is a "$4" record and points to "$5""}' | tail -n 1
    dig "lb-01.$1" | grep -A1 'ANSWER SECTION:' | awk '{print "The subdomain lb-01 is a "$4" record and points to "$5""}' | tail -n 1
    dig "web-01.$1" | grep -A1 'ANSWER SECTION:' | awk '{print "The subdomain web-01 is a "$4" record and points to "$5""}' | tail -n 1
    dig "web-02.$1" | grep -A1 'ANSWER SECTION:' | awk '{print "The subdomain web-02 is a "$4" record and points to "$5""}' | tail -n 1

elif [ "$#" -eq 2 ]; then

    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{split ($1, Subdo, "."); print "The subdomain "Subdo[1]" is a "$4" record and points to "$5""}' | tail -n 1

fi
