#!/usr/bin/env bash
# linea 7 va al archivo .html y cambia todo lo que hay por "Holberton school"
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
