#!/usr/bin/env bash
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo chmod -R 755 /var/www/html/index.nginx-debian.html
# sudo ufw allow 'Nginx HTTP'
# linea 7 va al archivo .html y cambia todo lo que hay por "Holberton school"
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
