#!/usr/bin/env bash
# Page Not Found
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i "/server_name _;/a \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent; " /etc/nginx/sites-available/default
sudo sed -i "/rewrite/ a \\\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}" /etc/nginx/sites-available/default
sudo service nginx restart
