#!/usr/bin/env bash
# configure web-02 to be identical to web-01 by configuring nginx so its http
# response contains a custom header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "/rewrite/ a \\\n\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i "/server_name _;/ a \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent; " /etc/nginx/sites-available/default
sudo sed -i "/rewrite/ a \\\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}" /etc/nginx/sites-available/default
sudo service nginx restart
