#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
n=1
while (( n <= 10 )) #another way while [$n -le 10], y para el incremento n=$(( n+1 ))
do
    echo "Holberton School"
    (( ++n ))
done
