#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
n=1
while (( n <= 10 ))
do
	if (( n == 4 ))
	then
		echo "bad luck"
    elif (( n == 8 ))
    then
        echo "good luck"
    else
        echo "Holberton School"
	fi
    (( n++ ))
done