#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user
pkill -f apache2
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 600 /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-available/default
sudo -u nginx /etc/init.d/nginx start
